auth_srv_sec:
    system: SY_PLADAPATH
    mapping_role:
        CONSULT-PLADAPATH: UTILISATEUR
        ADMIN-PLADAPATH: ADMINISTRATEUR
    mapping_default_role: ROLE_CONS
    bouchon_redirect: app_accueil