#index:
#    path: /
#    controller: App\Controller\DefaultController::index

traitment_create:
    path: '/traitment/create'
    controller: App\Controller\TraitementController::createTraitment
    methods: ['POST']

traitment_delete:
    path: '/traitment_delete/{id}'
    controller: App\Controller\TraitementController::deleteTraitment
    methods: ['GET']

traitement_delete:
    path: '/traitement_delete/{id}'
    controller: App\Controller\CalendarController::deleteTraitement
    methods: ['GET']

message_delete:
    path: '/message/delete/{id}'
    controller: App\Controller\MessageController::deleteMessage
    methods: ['GET']
    
caisse_delete:
    path: '/caisse_delete/delete/{id}'
    controller: App\Controller\CaisseController::deleteCaisse
    methods: ['GET']

poolvm_delete:
    path: '/poolvm/delete/{id}'
    controller: App\Controller\PoolVmController::deletePoolVm
    methods: ['GET']

vm_delete:
    path: '/vm/delete/{id}'
    controller: App\Controller\VmController::deleteVm
    methods: ['GET']

scenario_delete:
    path: '/scenario/delete/{id}'
    controller: App\Controller\ScenarioController::deleteScenario
    methods: ['GET']

process_delete:
    path: '/process/delete/{id}'
    controller: App\Controller\ProcessController::deleteProcess
    methods: ['GET']

edit_traitement:
    path: '/edit_traitement/{id}'
    controller: App\Controller\TraitementController::editTraitement
    methods: ['GET', 'POST']
    
traitment_cloture:
    path: '/traitment_cloture/{id}'
    controller: App\Controller\CalendarController::clotureTraitement
    methods: ['POST']
    
traitment_erreur:
    path: '/traitment_erreur/{id}'
    controller: App\Controller\CalendarController::erreurTraitement
    methods: ['POST']

delete_cloture:
    path: '/delete_cloture/{id}'
    controller: App\Controller\CalendarController::deleteCloture
    methods: ['POST']
    
delete_error:
    path: '/delete_error/{id}'
    controller: App\Controller\CalendarController::deleteError
    methods: ['POST']
    
info_caisse:
    path: '/info_caisse/{id}'
    controller: App\Controller\AccueilController::infoCaisse
    methods: ['GET']

dossier_statistiques:
    path: /dossier_statistiques/{year}
    controller: 'App\Controller\StatsController::dossierStatistiques'
    methods: ['GET']

dossier_stat_controller:
    path: '/dossier_statistiques_per_pool/{year}/{poolVM}'
    controller: App\Controller\StatsController::statsByPool
    methods: ['GET']
